name: create release PR
on:
  push:
    branches:
      - mainline
jobs:
  tag-release:
    name: Tag release based on CHANGELOG
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: release pr
        run: |
          yarn install
          git config user.name "github-action-automation"
          git config user.email "aws-chamonix-dev@amazon.com"
          yarn run standard-version
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev-release
          destination_branch: develop
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}