name: create release PR
on:
  push:
    branches:
      - mainline
jobs:
  tag-release:
    name: Tag release based on CHANGELOG
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: release pr
        run: |
          yarn install
          yarn run standard-version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: develop
          branch: dev-release