name: Tag release, publish to NPM
on: [workflow_dispatch]
jobs:
  tag-release:
    name: Tag release based on CHANGELOG
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.MERGE_TOKEN}}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Tag release
        run: |
          yarn --frozen-lockfile
          yarn run release
          git tag v$(jq '.version' -r package.json)
          git push origin --tags